### ISSUE TITLE
Touchpad lock doesn't work on newest firmware

### ISSUE THREAD

**Issue by ahoneybun** [system76/firmware-open#1]
The firmware was flashed on Friday 8/23/19 and build that day as well. The feature doesn't work and neither does the indicator. Running on Pop 19.04 with the latest updates. 

[system76-packages.txt](https://github.com/system76/firmware-open/files/3538933/system76-packages.txt)

[dmidecode.txt](https://github.com/system76/firmware-open/files/3538931/dmidecode.txt)

**Comment by ahoneybun** [comment]
Tested both Wayland and Xorg with the same results.

**Comment by leviport** [comment]
Touchpad disable hotkey currently works on all 3 of our current OSes on the Darter.
