### ISSUE TITLE
Darter: No display via USB type C (Thunderbolt)

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#11]
Plugging in a (laptop)usb-c to DisplayPort(monitor) cable to get an external display does not work. On the darp5 and galp3-c a setting in the BIOS needs to be made to enable the external display to work: Advanced->Advanced Chipset Control->DDI Control: DDI to TBT (was DDI to mDP).

**Comment by jackpot51** [comment]
Fixed by https://github.com/pop-os/system76-power/pull/110
