### ISSUE TITLE
ACPI Error prevents install on Asus TUF A17

### ISSUE THREAD

**Issue by yendao42** [system76/firmware-open#119]
When I try to install pop-os on Asus TUF706IU the install hangs with an ACPI related error (see attached image).  
I've been able to get Kubuntu installed and working properly by adding acpi_osi=native.
![pop-os_acpi_error](https://user-images.githubusercontent.com/8915905/90012241-a586b600-dc68-11ea-9d83-6a7bb784fc88.jpg)

**Comment by crawfxrd** [comment]
This repo is for issues with System76 Open Firmware and related projects.

Please open an issue in a relavant [pop-os](https://github..com/pop-os) project.
