### ISSUE TITLE
Unable to reach systemd-boot menu

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#13]
I am unable to reach the systemd-boot menu without setting a timeout (show that it is displayed). Usually(with proprietary firmware) I have success selecting the boot option from the bios menu and then pressing <kbd>Space</kbd>. That does not work here. I also tried just pressing <kbd>Space</kbd> or <kbd>Shift</kbd> when the system is booting but pressing just about any key takes me into the bios menu.

**Comment by jackpot51** [comment]
Potentially fixed in https://github.com/system76/firmware-open/commit/6a2e7d4f851aa2c85fee2b9798a43117ab0cafac which brought in https://github.com/system76/edk2/commit/bc688ee06668b1b4a3d3795ee40d5dec90c07182
