### ISSUE TITLE
scripts/deps.sh hangs

### ISSUE THREAD

**Issue by curiousercreative** [system76/firmware-open#147]
Installing dependencies via `scripts/deps.sh` hangs on a fresh system, fresh repo clone and submodule init. Sorry to lack details and output, can attempt to add later if this is not immediately reproducible.

**Comment by crawfxrd** [comment]
Submodule clones? Far too often, I see the speed go to <30 KiB/s (down to 2 KiB/s). `--progress` should be added to show it's kind of doing something.

**Comment by crawfxrd** [comment]
Submodule clones now show progress. Now you'll see the very slow transfer speeds instead of the script seeming to hang.
