### ISSUE TITLE
Feature request: Live update "One Time Boot" menu when new device is plugged in

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#15]
Similar to the proprietary INSYDE firmware, it would be nice for the "One Time Boot" menu to recognize when a new bootable device is connected/disconnected and update the boot options accordingly.

**Comment by crawfxrd** [comment]
The newer edk2 code in `wip/uefipayloadpkg` seems to trigger an event on device insertion/removal which updates this list. Still have to exit and re-enter the form to see the change, though.

**Comment by crawfxrd** [comment]
I'm not seeing a way to register a notify function for device topology changes, like `RegisterKeyNotify()` of `EFI_SIMPLE_TEXT_INPUT_EX_PROTOCOL`.

**Comment by crawfxrd** [comment]
I've hacked up MdeModulePkg to get this working with DisplayEngineDxe. I'll need to investigate the behavior with firmware-setup.

**Comment by crawfxrd** [comment]
Released in with 2021-01-19_d6d37c0.
