### ISSUE TITLE
lemp9: ACPI BIOS Error (bug) notice at boot

### ISSUE THREAD

**Issue by metaphys** [system76/firmware-open#152]
since the last firmware update (2021-01-19_d6d37c0), I have the following warning at boot time:
ACPI BIOS Error (bug): Could not resolve symbol [^^XBCL], AE_NOT_FOUND (20200925/psargs-330)
ACPI Error: Abording method \_SB.PCI0.GFX0.LCD0._BCL due to previous error (E_NOT_FOUND) (20200925/psparse-529)
seems harmless but is ugly :/

**Comment by bflanagin** [comment]
Looking into it now. Do you have any external hardware connected to your Lemur? Docking station,external monitor,etc.

**Comment by metaphys** [comment]
I have an external keyboard that is nearly always plugged in. (Ouch I don’t remember but I might very well have let it connected while performing the update. Not smart…)
yeah the system react correctly to ac being disconnected/reconnected

**Comment by bflanagin** [comment]
@metaphys nah, I don't think having it connected during the firmware update matters, I was more concerned about any external displays given whats being reported by the system. 
I'll keep testing but I'm not seeing the error on my lemp9. When does the message appear on your machine?

**Comment by metaphys** [comment]
this happen right after kernel selection in grub and before grub ask for my partition password.

**Comment by metaphys** [comment]
I’m having this on debian with the kernel from the ubuntu repo. Are there maybe some specific linux parameter that should be pass through grub?

**Comment by crawfxrd** [comment]
Were these fixed with the 2021-03-11 release?

**Comment by metaphys** [comment]
absolutely, thank you very much!
