### ISSUE TITLE
galp5 4k @ 120Hz HDMI TV capped at 30Hz

### ISSUE THREAD

**Issue by jackpot51** [system76/firmware-open#157]
HDMI 2.0 should support 4k @ 60 Hz, HDMI 2.1 should support 4k @ 120Hz. Confirm that the HDMI port is configured correctly

**Comment by leviport** [comment]
Let me know if you need anything tested. I have a 4K 60Hz display and an HDMI 2.1 cable, as well as the UMA galp5 and the 1650Ti galp5.

**Comment by jackpot51** [comment]
@leviport please check what framerate you can select with those two units

**Comment by leviport** [comment]
I can't select 60Hz on either.

1650Ti:
![2021-02-15_09-38](https://user-images.githubusercontent.com/13512097/107974596-112d4100-6f74-11eb-9b14-8ee1a8e3f681.png)

UMA
![2021-02-15_09-55](https://user-images.githubusercontent.com/13512097/107974609-168a8b80-6f74-11eb-8fd5-2c73967633ea.png)

I'm going to try to confirm that this setup will do 60Hz over HDMI at all. It is an older display, and my HDMI 2.1 cable wasn't particularly expensive.

**Comment by jackpot51** [comment]
@leviport @jacobgkau @thomas-zimmerman I believe this issue also affects the darp7. But not the lemp10. Can this be confirmed?

I will prepare a firmware update that should fix both

**Comment by jacobgkau** [comment]
Confirmed, lemp10 lets me use a 4k display at 60Hz, darp7 and galp5 currently limit to 30Hz. Testing the firmware updates now.
