### ISSUE TITLE
BIOS menu: `Boot Default` description over-verbose, could be simplified

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#16]
Currently the description for the `Boot Default` BIOS menu option reads `This selection will direct the system to continue to booting process`. This feels very complex and potentially too verbose to clearly describe to a user what this option does.

It was also noticed that the other two BIOS menu options are written in second person ("this menu will take you to..."). For better consistency, these options should probably either avoid "you" or use it for all three menu options.

Ideas that might be better:
`This selection will direct the system to boot`
`This selection will direct the system to the booting process".

For what it is worth, the current phrasing is what is currently listed on INSYDE proprietary firmware so potentially this is a non-issue.

**Comment by jackpot51** [comment]
Addressed in https://github.com/system76/edk2/commit/3da7ffcc96f97fcb16300c8e2e6bfba57f5bdaa4
