### ISSUE TITLE
Oryp6: slow keyboard at encryption screen

### ISSUE THREAD

**Issue by leviport** [system76/firmware-open#161]
I've seen this intermittently in all graphics modes except for Integrated. When I boot and try to unlock my encrypted disk, keypresses don't seem to register unless I hold the key for about half a second. If I type my passphrase normally, it shows that only a couple characters got picked up. This is on Pop!_OS 20.10, but I have also seen it on Pop!_OS 20.04.

**Comment by crawfxrd** [comment]
Dup of #156?

**Comment by leviport** [comment]
Looks like it, yeah. Whoops!

**Comment by leviport** [comment]
I edited my original issue. I have only seen this happen in Compute mode lately. I used to see it in Hybrid and Nvidia, but it seems like that's gotten better.
