### ISSUE TITLE
lemp9: unable to undervolt

### ISSUE THREAD

**Issue by lead4good** [system76/firmware-open#162]
Using this [undervolt tool](https://github.com/georgewhewell/undervolt), I am able to set the temperature target as well as the powerlimit, however any attempt to undervolt core, gpu etc. fails.
```
$ sudo ./undervolt.py  --core -50 --cache -50
ERROR:root:Failed to apply core: set -49.8046875, read 0.0
```
System is stock PopOS 20.10

**Comment by lead4good** [comment]
I've read that many hardware manufacturers have started disabling undervolt due to the plundervolt vulnerability. How does this relate to coreboot? Could it be that the newer FSP/Microcode disables undervolting by default?

**Comment by crawfxrd** [comment]
Closing in favor of #201, which has more discussion.
