### ISSUE TITLE
BIOS menu: `One Time Boot` and `Change Boot Order` menu descriptions refer to old phrasing

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#17]
Currently the description for the `One Time Boot` menu is: `This selection will take you to the Boot Manager`. There is no other reference to a `Boot Manager` in this BIOS menu.

A similar issue exists for the `Change Boot Order` menu described: `...will take you to Boot Maintenance Manager` where `Boot Maintenance Manager` is not referenced anywhere else.

**Comment by jackpot51** [comment]
Addressed in https://github.com/system76/edk2/commit/3da7ffcc96f97fcb16300c8e2e6bfba57f5bdaa4
