### ISSUE TITLE
NV41MB/NV41ME - No Thunderbolt and hot CPU after flashing open firmware and s76 EC

### ISSUE THREAD

**Issue by tgroborsch** [system76/firmware-open#175]
Hi there,
I noticed that with the galp5 the platform for NV41Mx was implemented.
Thanks to the good flashing instructions I was able to flash BIOS and EC. The device was then able to update the firmware from pop!os and also by using the flash_internal method and flashing via USB.

BUT unfortunately Thunderbolt stopped working. My HP G2 Thunderbolt dock is not recognized by the system. Besides charging via USB-C nothing from the dock worked (no ethernet, no usb-devices, no video-out).
Also the CPU got hot without load (according to psensors 87 °C), resulting in the fans kicking off.

Luckily I backed up the OEM bios and EC and reverted back.
Afterwards Thunderbolt started working again and CPU behalves normal again.

Is there a small flashing detail I'm missing here?
As everything went back to normal after reverting back to OEM I assume there is no hardware defect present.

I know this is not your sold hardware - would I have lived in the US I would have happily purchased your product (maybe you extend your business to germany in the future?). And I much apprechiate that you keep your development open source!

**Comment by jackpot51** [comment]
Our galp5 firmware will not function on your laptop, you need a genuine system76 product
