### ISSUE TITLE
Build failes

### ISSUE THREAD

**Issue by feldim2425** [system76/firmware-open#176]
Full output here: https://pastebin.com/EEv6MGtg

The QEMU build failes, I also tested "gaze15" and "oryp5" but they both fail with the same error.

System:
Fedora 33 KDE Spin
Python 3.9.2
Rustup 1.23.1
Cargo 1.47.0-nightly

**Comment by crawfxrd** [comment]
edk2 doesn't work with python3.9. You need to patch edk2 or use an older version of Python.
