### ISSUE TITLE
Provide install-time option to disable the ME

### ISSUE THREAD

**Issue by DemiMarie** [system76/firmware-open#197]
On new Intel platforms, disabling the ME comes at a penalty in standby power draw.  Some users (like myself) would prefer that the ME be disabled for enhanced security, while others need the reduced standby power use.  Therefore, I would like to be able to configure this at system setup time.

**Comment by crawfxrd** [comment]
It could probably be enabled/disabled by a CMOS option that could be set with nvramtool.
