### ISSUE TITLE
BIOS Menu: Extra menu when changing boot order

### ISSUE THREAD

**Issue by leviport** [system76/firmware-open#21]
After selecting "Change Boot Order" from the main menu, I am taken to a menu with an option called "Change Boot Order", with two other options "Commit Changes and Exit" and "Discard Changes and Exit". To change or view the boot order, I have to hit Enter again, rearrange the boot items, hit Enter once more, then select "Commit Changes and Exit". This menu in between the main menu and the boot order list feels like an unnecessary extra step since I cannot actually change the boot order without going one level deeper into the menu.

**Comment by crawfxrd** [comment]
Is the current implementation sufficient to resolve this?

**Comment by leviport** [comment]
I think it could still be improved, but it is much better than it was when I opened this issue. I'll close it for now.
