### ISSUE TITLE
oryp5

### ISSUE THREAD

**Issue by kevr** [system76/firmware-open#210]
Hello guys. What exactly needs to be done to get the open firmware working on the oryp5? I would love to use it and have experience writing software.

I'm very interested in working on a patch for this. Is this something you guys would be open to (outside contributions)?

Thanks for your time!

**Comment by crawfxrd** [comment]
- #132: NVIDIA GC6 2.1 support
  - Ref: system76/coreboot#38
- #154: TAS5825M initialization error
  - Ref: https://github.com/system76/smart-amp
- EC: Fan curve improvements
  - Ref: system76/ec#164, system76/ec#167, system76/ec#190

**Comment by kevr** [comment]
Thank you very much! I'll begin working on it within days.

**Comment by kevr** [comment]
Bit of a stopper; unfortunately, I need another laptop before I can attempt messing with this stuff on my oryp5. I need at least one laptop to continue working on things. But, I will be saving up and purchasing a new affordable laptop, and when I do, I will immediately jump on this.

**Comment by DraconicNEO** [comment]
Any progress on getting open firmware working on the oryp5? I know many oryp5 users (including myself) would be very happy to finally have open firmware.

**Comment by crawfxrd** [comment]
Need to test the if the GPU works with the coreboot driver rewrite.

Need to test if system76/smart-amp#12 fixes the problems with the speakers.

**Comment by crawfxrd** [comment]
GPU is not detected after the rewrite.

#154 is still a problem.

**Comment by crawfxrd** [comment]
Should be in a good state to test with system76/coreboot#123.

**Comment by crawfxrd** [comment]
Dev work was complete and was working when I returned the oryp5 (minus the parts I broke :slightly_smiling_face:).

Release PR is open, if we ever get around to it..
