### ISSUE TITLE
Deleting Boot Entry Options?

### ISSUE THREAD

**Issue by davidsaulrodriguez** [system76/firmware-open#211]
It seems there is no way to remove an old boot entry option from Coreboot based bootloader.

Am I missing something or is this feature not implemented yet and am I just stuck with old bootloader entries.

For example: If I installed Fedora and then later blew that away and reinstalled Pop!_OS, the Fedora boot entry is still there when I select **_One Time Boot_**

**Comment by crawfxrd** [comment]
Management of EFI variables is explicitly disabled in edk2, with the exception of changing `BootOrder`.

Use `efibootmgr` from the OS to manage boot options in NVRAM.
