### ISSUE TITLE
BIOS Menu: "Esc=Exit" on main menu does nothing

### ISSUE THREAD

**Issue by leviport** [system76/firmware-open#22]
On the main BIOS menu, an option is shown in the bottom bar that says "Esc=Exit", however hitting the escape key at the main menu does not exit the BIOS. Seeing that prompt makes me expect the escape key to exit the BIOS menu and begin booting normally. To boot normally, I have to select "Boot Default" instead.

**Comment by crawfxrd** [comment]
Would the preferred behavior be to not show `Esc=Exit` on the front page, or have Esc do something else (boot default entry)?

**Comment by brs17** [comment]
@crawfxrd I like the idea of `Esc` escaping the firmware menu and booting the default boot entry.

**Comment by crawfxrd** [comment]
This may actually be a problem, depending on user behavior. If they hold or repeatedly press Esc, they'll go into the setup and then immediately exit to the default boot.

**Comment by jackpot51** [comment]
That's a good point @crawfxrd.

**Comment by jackpot51** [comment]
@brs17 any thoughts? Should we revert the change and instead remove the Esc=Exit on the front page?

**Comment by brs17** [comment]
Yeah, @crawfxrd that is a very good point. I think the reason some IBVs get away with it is by having a confirmation screen upon exit. Let's just get rid of `Esc=Exit`.
