### ISSUE TITLE
gaze16: touchpad not working in Windows

### ISSUE THREAD

**Issue by jacobgkau** [system76/firmware-open#226]
The touchpad is working in Linux, but not in Windows. I've installed the two drivers listed at https://github.com/system76/windows-drivers#gazelle-gaze16.

I noticed this device in the Device Manager that looks like it could be related:
![gaze16-i2c](https://user-images.githubusercontent.com/7199422/129063879-7174c4f0-a12d-4759-994e-f2aed846960b.PNG)

**Comment by AnthonyMFL** [comment]
Same problem

**Comment by Seibz** [comment]
In testing the Gazelle model gaze16, the touchpad also does not work in Fedora 34 with all patches applied, on kernel 5.13.10-200 and with the System76 drivers installed from https://copr.fedorainfracloud.org/coprs/szydell/system76/
[system76-logs.zip](https://github.com/system76/firmware-open/files/7017641/system76-logs.zip)

**Comment by mlandry1** [comment]
same problem here in Windows.

**Comment by JCDetwiler** [comment]
Having the same problem in Arch Linux on gaze16-3050.

**Comment by jackpot51** [comment]
We will release firmware fixing this soon.

**Comment by dj911ice** [comment]
The firmware update that was pushed fixed the issue! Christmas really came this year!
