### ISSUE TITLE
gaze16 - Unidentified devices under Windows

### ISSUE THREAD

**Issue by mlandry1** [system76/firmware-open#233]
I've installed the two drivers listed at https://github.com/system76/windows-drivers#gazelle-gaze16.

But two devices still appears as unknown in Windows 10 Pro V20H2 Build 19042.1165.

![image](https://user-images.githubusercontent.com/11726926/131227844-cad77f1f-422f-4c97-9f58-518ca2559c8d.png)
![image](https://user-images.githubusercontent.com/11726926/131227852-c11d0f17-19ce-4e28-8f23-a8a86a0ef1ea.png)

**Comment by jacobgkau** [comment]
Some unidentified devices in Device Manager are expected when using Windows on Open Firmware machines. There is only an issue if functionality is not working. (For gaze16, we do currently have https://github.com/system76/firmware-open/issues/226 open to track the touchpad not working; even once that is fixed, I would still expect the unidentified ACPI items to show up in Device Manager.)

**Comment by crawfxrd** [comment]
- INTC1026: Tiger Lake IPC Controller device (`coreboot/src/soc/intel/tigerlake/pmc.c`)
- 17761776: System76 EC ACPI device (`coreboot/src/ec/system76/ec/acpi/s76.asl`)

**Comment by crawfxrd** [comment]
Issue is fixed. Track #340 to see if it has been released.
