### ISSUE TITLE
oryp6 - Keyboard sometimes not activating on post after multiple hard resets while plugged in

### ISSUE THREAD

**Issue by JoonasC** [system76/firmware-open#236]
Sometimes after hard resetting multiple times (long pressing on power button) during boot, the keyboard will not be activated on post until the laptop is unplugged.

**Comment by crawfxrd** [comment]
How frequently are you able to reproduce this? Does the keyboard not work at all, even when booted to the OS? Are there errors/warnings in dmesg related to the keyboard?

**Comment by JoonasC** [comment]
I'm unable to test whether it works when the OS is fully booted, because of disk encryption, but since it doesn't work during the whole boot process i think it's safe to say that it wouldn't work

**Comment by JoonasC** [comment]
This isn't a big problem though, as it only happens when the laptop is hard reset multiple times during boot (before and after POST), and it starts working again when the laptop is unplugged. It's just an interesting corner case that I thought I'd report.

**Comment by JoonasC** [comment]
I also have an external keyboard and display plugged in, dunno if that could have something to do with it.

**Comment by crawfxrd** [comment]
Are you on firmware version `2021-07-20_93c2809`? (Can check with `dmidecode -t bios` or Firmware panel in Settings.)

**Comment by JoonasC** [comment]
Nope

**Comment by JoonasC** [comment]
Running 2021-03-16_7c3e89e

**Comment by JoonasC** [comment]
Firmware manageri doesn't show new updates

**Comment by crawfxrd** [comment]
A bug was recently fixed in system76-firmware that was preventing updates. You can delete `/var/cache/system76-firmware-daemon/tail` and check then Firmware panel in Settings to get the update.

**Comment by JoonasC** [comment]
I'm running ubuntu, and followed the https://support.system76.com/articles/install-ubuntu guide

**Comment by JoonasC** [comment]
Maybe I did something wrong?

**Comment by JoonasC** [comment]
OK, nvm. It's showing updates now

**Comment by JoonasC** [comment]
The latest firmware upgrade seems to have fixed the issue, thanks.
