### ISSUE TITLE
Can't build firmware for oryp6

### ISSUE THREAD

**Issue by FengXi7420** [system76/firmware-open#251]
Stucked at make: *** [src/drivers/intel/fsp2_0/Makefile.inc:77：build/Fsp_M.fd] 错误 127

**Comment by crawfxrd** [comment]
Install python2 and make sure the `/usr/bin/python2` symlink exists.

**Comment by FengXi7420** [comment]
> Install python2 and make sure the `/usr/bin/python2` symlink exists.

thank you
