### ISSUE TITLE
galp4: Keyboard stops working on suspend/resume

### ISSUE THREAD

**Issue by jackpot51** [system76/firmware-open#26]
@WatchMkr reported the keyboard sometimes failing to work on resume. @system76/quality-assurance could you test on the lab systems as well?

**Comment by brs17** [comment]
@jackpot51 it might definitely be a "sometimes" thing. We have not seen it through our testing thus far. It does sound familiar to the issue some people have had with other Darter Pros and Galago Pros. We will keep an eye out for it.

**Comment by leviport** [comment]
I have not seen this in quite a while, so we can reopen it if it comes back.
