### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by wwahammy** [system76/firmware-open#263]
First off, I love my System76 laptop and your company's commitment to open source. I was hoping you could clarify and add a license to this repo as well as all the associated repos. It's not really clear what rights we have as users. I assume you intended to put this under an open source license (minus the icky binaries which are, sadly, unavoidable). Would you be able to clarify what the license is?

**Comment by crawfxrd** [comment]
All submodules should already have licenses.

**Comment by jackpot51** [comment]
Please see the licenses of each component - coreboot, EDK2, and each of the apps have different open source licenses. Some components like the FSP have a freely redistributable closed source license.
