### ISSUE TITLE
Oryp8 ME Disable

### ISSUE THREAD

**Issue by Localacct21** [system76/firmware-open#266]
Will I be able to disable ME in the near future with a Oryp8?

**Comment by crawfxrd** [comment]
It's already disabled.

**Comment by Localacct21** [comment]
No its not. https://user-images.githubusercontent.com/78702586/146661876-60634f82-da45-4fdf-bbab-76b9b076328b.mp4

**Comment by crawfxrd** [comment]
Oh, right. It wasn't released.

It will be disabled by default when #260 is released, but I'm closing this as a duplicate of #197.

**Comment by crawfxrd** [comment]
Released with 2022-09-07_74e75ff.
