### ISSUE TITLE
Oryp8 TPM Disabled

### ISSUE THREAD

**Issue by Localacct21** [system76/firmware-open#279]
- Model: Oryp8
- BIOS Version:	2021-09-23_b9b0e89
- EC version: 2021-09-23_b9b0e89
- OS: Windows 10

### Steps to reproduce

TPM is turned off even though the BIOS reports its turned on.

![Screenshot (6)](https://user-images.githubusercontent.com/78702586/149243025-c69664ea-bbd7-49e1-8039-1b5d5e731d78.png)

boot windows

### Expected behavior

TPM should be active

How do i turn it on?

**Comment by Localacct21** [comment]
after searching i cannot find anything stating how to turn it on. the bios reports its on. windows reports its off
![Screenshot (7)](https://user-images.githubusercontent.com/78702586/149579317-2942f05c-ab84-47d5-9eb1-b8fa9b1780ad.png)
.

**Comment by crawfxrd** [comment]
The TPM device is enabled on all models.

If you boot Linux, does it get detected?

```
sudo dmesg | grep tpm
ls /dev/tpm*
ls /sys/class/tpm/tpm*/
```

**Comment by Localacct21** [comment]
![Screenshot from 2022-01-14 15-50-29.png](https://user-images.githubusercontent.com/78702586/149583871-f5e6c75c-a288-4697-b72e-f72aa2b23722.png)

This was the result

**Comment by Localacct21** [comment]
> The TPM device is enabled on all models.
> 
> If you boot Linux, does it get detected?
> 
> ```
> sudo dmesg | grep -i tpm
> ls /dev/tpm*
> ls /sys/class/tpm/tpm*/
> ```

![Screenshot from 2022-01-14 15-50-29.png](https://user-images.githubusercontent.com/78702586/149583930-39959bc3-2788-4d14-8360-de5000581df6.png)


This was the result.

**Comment by Localacct21** [comment]
So linux is saying the same thing. The TPM chip is not functioning

**Comment by crawfxrd** [comment]
I'll have to flash back to the current release to check, since it is working on `master` on my unit.


If you are able to build cbmem, you can dump the coreboot log to check if it fails to initialize the device.

```
make -C coreboot/util/cbmem
sudo ./coreboot/util/cbmem/cbmem -c > cbmem.txt
```

I don't remember what the logs would be, but grepping for "TPM" should be sufficient.

**Comment by Localacct21** [comment]
I cannot compile I'm getting errors

**Comment by crawfxrd** [comment]
I flashed back to `2021-09-23_b9b0e89` and can confirm that TPM detection is broken.

coreboot logs:

```
tis_probe: No TPM device found
tlcl_lib_init: tis_init returned error
TPM: Can't initialize.
```

**Comment by Localacct21** [comment]
So is this why it's not being reported to windows or Linux? Because the TPM detection is broken In this version of coreboot? When will this be fixed? The laptop is advertised as having TPM.

**Comment by crawfxrd** [comment]
> So is this why it's not being reported to windows or Linux?

Yes. coreboot can't find and initialize the device, so the OS can't see it either.

> When will this be fixed?

This issue is fixed, but there are a couple other issues that need to be addressed as well before making a release.

**Comment by Localacct21** [comment]
Could you please direct me on how to compile the master With Intel ME. I tried compiling before and it worked just fine but I disabled ME in the process. I need Intel ME for some of the software I use to work.

**Comment by Localacct21** [comment]
> If you are using `2021-09-23_b9b0e89`, IME is hardcoded to be disabled.
> 
> If you are using `master`, see [`docs/intel-me.md#configuring`](https://github.com/system76/firmware-open/blob/239e2cbaed0d9ec0fa8a9f75b5a787f5a744147a/docs/intel-me.md#configuring).

Thank you Tim. Yes I want to recompile Master to have Intel ME.

**Comment by crawfxrd** [comment]
Fixed with `2022-09-07_74e75ff`.
