### ISSUE TITLE
Disable Intel M.E. for Galago Pro and Darter Pro models

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#28]
Determine how to disable the Intel M.E. with the latest 14.x.x.x version.

**Comment by jackpot51** [comment]
This was addressed in https://github.com/system76/firmware-open/commit/fbe457ab742f57a18d73fba79491240378b41967, which pulled in https://github.com/system76/coreboot/commit/015f42bbe42c39b2861efd00c876ef19d2124d54

**Comment by brs17** [comment]
On firmware `2651a70`, `/dev/mei0` does not exist on either the galp4 and darp6.
