### ISSUE TITLE
> Smoothing ramp up/ramp down curves can result in even slower ramp-up reaction than there is right now.

### ISSUE THREAD

**Issue by Localacct21** [system76/firmware-open#286]
> Smoothing ramp up/ramp down curves can result in even slower ramp-up reaction than there is right now.

This is why the reaction time was reduced, as I mentioned. The delay you currently see was to prevent short bursts of high fan speed. That's no longer as much of an issue with smoothing, so the fans will respond slightly quicker.

A 10-second "running maximum" would imply a 10-second delay in response for decreases in temperature. Using an average instead of the current temperature would also add more delay, as it would take longer for the average to rise/fall than the actual temperature.

The smoothing + slight remaining delay created something that felt like an average last time I tested it, so I'd recommend you wait and try it out. The upcoming firmware update is for all Open Firmware laptops and will still be in testing for a little while, so if you want to give it a try now, you can install Rust using the command on [this website](https://rustup.rs/) and then build/flash on your Oryx Pro using these commands:

```
git clone https://github.com/system76/firmware-open
./scripts/update.sh
./scripts/deps.sh
./scripts/build.sh oryp7
./scripts/flash.sh oryp7
```

The flashing script will power off your machine, so save any work you have open before running it. As long as you remain plugged into the charger through this entire process, it should be fairly low-risk. Once you're on the self-built firmware, your Oryx Pro will prompt you for a firmware "update," which you can install at any time through the GUI to go back to the regular published firmware.

If you find that the fan behavior is still not satisfactory, this issue should probably be transferred to the EC repository, since that is where most of the work on fan behavior happens. There's also some discussion about fan curves here: https://github.com/system76/ec/issues/180

_Originally posted by @jacobgkau in https://github.com/system76/firmware-open/issues/224#issuecomment-889238745_

when following this to build the firmware i get these errors that are contained in the log.txt
[log.txt](https://github.com/system76/firmware-open/files/7919963/log.txt)
s

**Comment by crawfxrd** [comment]
Please keep the comments in #224 instead of making a new issue.
