### ISSUE TITLE
System freezes when selecting any BIOS menu option

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#29]
With firmware `2019-10-03_01c09f0`, the BIOS menu hangs when trying to select either the `One Time Boot` or `Change Boot Order` option. A hard poweroff is required to get out of this frozen state.

**Comment by brs17** [comment]
> With firmware `2019-10-03_01c09f0`, the BIOS menu hangs when trying to select either the `One Time Boot` or `Change Boot Order` option. A hard poweroff is required to get out of this frozen state.

Edited stating selecting `One Time Boot` or `Change Boot Order` both hang.

**Comment by brs17** [comment]
This firmware was flashed by building firmware-open and flashing it using popsicle.

**Comment by jackpot51** [comment]
This may have been caused by boot menu pollution which was fixed, but there were leftover entries on the system

I cleared the NVRAM and it appears to be working now.

**Comment by jackpot51** [comment]
Related to #27

**Comment by brs17** [comment]
Since this issue may not be only caused by #27, I am going to reopen this issue.

**Comment by jackpot51** [comment]
Workaround in https://github.com/system76/firmware-update/commit/1db61997f32f394820aef53cf241b3842d4e5144

**Comment by brs17** [comment]
Looks good on `2019-10-08_3869d9c`
