### ISSUE TITLE
lemp10 fails to suspend in non-Pop!_OS systems and Kernels if SATA SSD is in second slot

### ISSUE THREAD

**Issue by happyplace** [system76/firmware-open#290]
- Model: lemp10
- BIOS version: 2021-07-20_93c2809
- EC version: 2021-07-20_93c2809
- OS: ONLY works on Pop!_OS

If I insert my WD BLUE 3D NAND SATA SSD M.2 2280 into the second slot of my laptop it will never suspend, aka the power indicator never goes into a blinking state, if I use any operating system that is not Pop!_OS or the Pop!_OS kernel for Ubuntu in the ppa. 

### Steps to reproduce

1. Have a factory configured lemp10
2. Insert SATA SSD M.2
3. Boot up a Fedora 35 install, this also works in the live environment
4. close the laptop lip
5. observe the laptop power indicator never goes into the blinking state

### Expected behavior

1. Install Any operating system
2. close laptop lid
3. have power indicator go into blinking state

### Actual behavior

The laptop light never goes into the blink state when I use Windows 10, Fedora, or Arch when I close the lid or manually press the suspend state

### Additional info

I've had the operating system in the live state and installed with full upgrades. My laptop is completely stock with the exception of the additional SATA SSD. I've tried manually install all of the previous firmware versions from git. I was even getting this behaviour on the 2022 version of the firmware that was released and then rolled back. The SATA SSD was not mounted in any of my Linux systems, and I tried suspending from an install that was on both SATA SSD and the SSD that shipped with the laptop.

**If I use any version of Pop!_OS or I install Ubuntu and use the System76 PPA the laptop CORRECTLY enters the suspend state, with blinking power indicator**

**Comment by crawfxrd** [comment]
Fixed with updated coreboot in fd9d73bdb9c8.
