### ISSUE TITLE
[Question] Oryp6 not getting latest firmware patches

### ISSUE THREAD

**Issue by JoonasC** [system76/firmware-open#296]
Is the Oryp6 not getting the latest firmware patches, such as updated coreboot, etc? Or is this a bug with the firmware manager? The latest version I see in the firmware manager is 2021-07-20_93c2809.

Btw, I am not running Pop Os. Instead I am running Linux Mint with the System76 drivers installed, which might possibly have something to do with this if this is indeed a bug.

**Comment by crawfxrd** [comment]
`2021-07-20_93c2809` is the latest release for oryp6.

**Comment by JoonasC** [comment]
Ok, just wanted to be sure.
