### ISSUE TITLE
BIOS Menu: Multiple internal drives are numbered strangely

### ISSUE THREAD

**Issue by leviport** [system76/firmware-open#30]
On the Galago with a 2.5" drive and an M.2 SATA drive, when I go to the One Time Boot menu, I see two options: "EFI Hard Drive" and "EFI Hard Drive 1". Would it be better to number them 1 and 2 instead?

![IMG_20191003_155826](https://user-images.githubusercontent.com/13512097/66167335-13009980-e5f7-11e9-985e-71e6ff108b0a.jpg)

**Comment by jackpot51** [comment]
Changed the 1's to 2's in https://github.com/system76/edk2/commit/1abe928d77ef58335c6af24f6da0fd1b6b4ca1e2

**Comment by jackpot51** [comment]
Discussion will move to #36
