### ISSUE TITLE
Open firmware boots into BIOS menu after updating firmware

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#31]
After updating firmware via USB, the system [boots straight into the BIOS menu](https://github.com/system76/firmware-update/blob/6080ff98f1686a51970f4c5e918b2e426f312f2c/src/app/mod.rs#L288). I understand the desire to want to do that for previous proprietary BIOS versions, but I am unsure of the use for this with open firmware.

**Comment by crawfxrd** [comment]
Was this fixed by system76/firmware-update#16?
