### ISSUE TITLE
galp4: long delay resuming from suspend

### ISSUE THREAD

**Issue by WatchMkr** [system76/firmware-open#32]
Oct  3 15:54:48 pop-os kernel: [ 2938.517757] iwlwifi 0000:00:14.3: Unhandled alg: 0x707
Oct  3 16:53:55 pop-os kernel: [ 6485.442249] pcieport 0000:02:01.0: bridge window [mem 0x00100000-0x000fffff] to [bus 04] add_size 400000 add_align 100000
Oct  3 16:53:55 pop-os kernel: [ 6485.442292] pcieport 0000:02:01.0: BAR 14: no space for [mem size 0x00400000]
Oct  3 16:53:55 pop-os kernel: [ 6485.442297] pcieport 0000:02:01.0: BAR 14: failed to assign [mem size 0x00400000]
Oct  3 16:53:55 pop-os kernel: [ 6485.442303] pcieport 0000:02:01.0: BAR 14: no space for [mem size 0x00400000]
Oct  3 16:53:55 pop-os kernel: [ 6485.442307] pcieport 0000:02:01.0: BAR 14: failed to assign [mem size 0x00400000]
Oct  3 17:43:35 pop-os kernel: [ 9465.342413] PM: suspend entry (deep)
Oct  4 13:58:18 pop-os kernel: [ 9465.353201] Filesystems sync: 0.010 seconds
Oct  4 13:58:18 pop-os kernel: [ 9465.353533] Freezing user space processes ... (elapsed 0.124 seconds) done.
Oct  4 13:58:18 pop-os kernel: [ 9465.478250] OOM killer disabled.
Oct  4 13:58:18 pop-os kernel: [ 9465.478253] Freezing remaining freezable tasks ... (elapsed 0.002 seconds) done.
Oct  4 13:58:18 pop-os kernel: [ 9465.480657] printk: Suspending console(s) (use no_console_suspend to debug)
Oct  4 13:58:18 pop-os kernel: [ 9465.483107] wlp0s20f3: deauthenticating from ac:86:74:bf:2e:10 by local choice (Reason: 3=DEAUTH_LEAVING)
Oct  4 13:58:18 pop-os kernel: [ 9467.374649] ACPI: EC: interrupt blocked
Oct  4 13:58:18 pop-os kernel: [ 9467.436309] ACPI: Preparing to enter system sleep state S3
Oct  4 13:58:18 pop-os kernel: [ 9467.438765] ACPI: EC: event blocked
Oct  4 13:58:18 pop-os kernel: [ 9467.438766] ACPI: EC: EC stopped
Oct  4 13:58:18 pop-os kernel: [ 9467.438796] PM: Saving platform NVS memory
Oct  4 13:58:18 pop-os kernel: [ 9467.438798] Disabling non-boot CPUs ...
Oct  4 13:58:18 pop-os kernel: [ 9467.441782] smpboot: CPU 1 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.447700] smpboot: CPU 2 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.451354] irq_migrate_all_off_this_cpu: 6 callbacks suppressed
Oct  4 13:58:18 pop-os kernel: [ 9467.451356] IRQ 122: no longer affine to CPU3
Oct  4 13:58:18 pop-os kernel: [ 9467.451366] IRQ 130: no longer affine to CPU3
Oct  4 13:58:18 pop-os kernel: [ 9467.451378] IRQ 160: no longer affine to CPU3
Oct  4 13:58:18 pop-os kernel: [ 9467.452410] smpboot: CPU 3 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.456141] IRQ 161: no longer affine to CPU4
Oct  4 13:58:18 pop-os kernel: [ 9467.456149] IRQ 162: no longer affine to CPU4
Oct  4 13:58:18 pop-os kernel: [ 9467.456155] IRQ 164: no longer affine to CPU4
Oct  4 13:58:18 pop-os kernel: [ 9467.456162] IRQ 166: no longer affine to CPU4
Oct  4 13:58:18 pop-os kernel: [ 9467.456168] IRQ 167: no longer affine to CPU4
Oct  4 13:58:18 pop-os kernel: [ 9467.456174] IRQ 168: no longer affine to CPU4
Oct  4 13:58:18 pop-os kernel: [ 9467.458341] smpboot: CPU 4 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.462077] IRQ 123: no longer affine to CPU5
Oct  4 13:58:18 pop-os kernel: [ 9467.463174] smpboot: CPU 5 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.469303] smpboot: CPU 6 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.474279] smpboot: CPU 7 is now offline
Oct  4 13:58:18 pop-os kernel: [ 9467.481087] ACPI: Low-level resume complete
Oct  4 13:58:18 pop-os kernel: [ 9467.481150] ACPI: EC: EC started
Oct  4 13:58:18 pop-os kernel: [ 9467.481150] PM: Restoring platform NVS memory
Oct  4 13:58:18 pop-os kernel: [ 9467.481990] Enabling non-boot CPUs ...
Oct  4 13:58:18 pop-os kernel: [ 9467.482024] x86: Booting SMP configuration:
Oct  4 13:58:18 pop-os kernel: [ 9467.482024] smpboot: Booting Node 0 Processor 1 APIC 0x1
Oct  4 13:58:18 pop-os kernel: [ 9467.482620] CPU1 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.482646] smpboot: Booting Node 0 Processor 2 APIC 0x2
Oct  4 13:58:18 pop-os kernel: [ 9467.483136] CPU2 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.483158] smpboot: Booting Node 0 Processor 3 APIC 0x3
Oct  4 13:58:18 pop-os kernel: [ 9467.483655] CPU3 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.483676] smpboot: Booting Node 0 Processor 4 APIC 0x4
Oct  4 13:58:18 pop-os kernel: [ 9467.484191] CPU4 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.484212] smpboot: Booting Node 0 Processor 5 APIC 0x5
Oct  4 13:58:18 pop-os kernel: [ 9467.484718] CPU5 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.484737] smpboot: Booting Node 0 Processor 6 APIC 0x6
Oct  4 13:58:18 pop-os kernel: [ 9467.485263] CPU6 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.485283] smpboot: Booting Node 0 Processor 7 APIC 0x7
Oct  4 13:58:18 pop-os kernel: [ 9467.485810] CPU7 is up
Oct  4 13:58:18 pop-os kernel: [ 9467.487996] ACPI: Waking up from system sleep state S3
Oct  4 13:58:18 pop-os kernel: [ 9468.538304] ACPI: EC: interrupt unblocked
Oct  4 13:58:18 pop-os kernel: [ 9468.601227] ACPI: EC: event unblocked
Oct  4 13:58:18 pop-os kernel: [ 9468.601652] usb usb3: root hub lost power or was reset
Oct  4 13:58:18 pop-os kernel: [ 9468.601656] usb usb4: root hub lost power or was reset
Oct  4 13:58:18 pop-os kernel: [ 9468.707598] nvme nvme0: Shutdown timeout set to 8 seconds
Oct  4 13:58:18 pop-os kernel: [ 9468.722290] nvme nvme0: 8/0/0 default/read/poll queues
Oct  4 13:58:18 pop-os kernel: [ 9468.847315] usb 1-10: reset full-speed USB device number 4 using xhci_hcd
Oct  4 13:58:18 pop-os kernel: [ 9468.918160] ata1: SATA link down (SStatus 4 SControl 300)
Oct  4 13:58:18 pop-os kernel: [ 9469.739943] psmouse serio2: synaptics: queried max coordinates: x [..5718], y [..4908]
Oct  4 13:58:18 pop-os kernel: [ 9469.859560] psmouse serio2: synaptics: queried min coordinates: x [1238..], y [956..]
Oct  4 13:58:18 pop-os kernel: [ 9550.943355] thunderbolt 0000:03:00.0: failed to send driver ready to ICM
Oct  4 13:58:18 pop-os kernel: [ 9550.943654] OOM killer enabled.
Oct  4 13:58:18 pop-os kernel: [ 9550.943656] Restarting tasks ... 
Oct  4 13:58:18 pop-os kernel: [ 9550.943873] usb 1-4: USB disconnect, device number 2
Oct  4 13:58:18 pop-os kernel: [ 9550.950463] done.
Oct  4 13:58:18 pop-os kernel: [ 9550.950685] Bluetooth: hci0: Bootloader revision 0.1 build 0 week 30 2018
Oct  4 13:58:18 pop-os kernel: [ 9550.951689] Bluetooth: hci0: Device revision is 2
Oct  4 13:58:18 pop-os kernel: [ 9550.951691] Bluetooth: hci0: Secure boot is enabled
Oct  4 13:58:18 pop-os kernel: [ 9550.951692] Bluetooth: hci0: OTP lock is enabled
Oct  4 13:58:18 pop-os kernel: [ 9550.951692] Bluetooth: hci0: API lock is enabled
Oct  4 13:58:18 pop-os kernel: [ 9550.951693] Bluetooth: hci0: Debug lock is disabled
Oct  4 13:58:18 pop-os kernel: [ 9550.951695] Bluetooth: hci0: Minimum firmware build 1 week 10 2014
Oct  4 13:58:18 pop-os kernel: [ 9550.951973] Bluetooth: hci0: Found device firmware: intel/ibt-19-0-1.sfi
Oct  4 13:58:18 pop-os kernel: [ 9551.286973] PM: suspend exit
Oct  4 13:58:20 pop-os kernel: [ 9552.667666] Generic Realtek PHY r8169-601:00: attached PHY driver [Generic Realtek PHY] (mii_bus:phy_addr=r8169-601:00, irq=IGNORE)
Oct  4 13:58:20 pop-os kernel: [ 9552.674663] Bluetooth: hci0: Waiting for firmware download to complete
Oct  4 13:58:20 pop-os kernel: [ 9552.675663] Bluetooth: hci0: Firmware loaded in 1684938 usecs
Oct  4 13:58:20 pop-os kernel: [ 9552.675713] Bluetooth: hci0: Waiting for device to boot
Oct  4 13:58:20 pop-os kernel: [ 9552.688819] Bluetooth: hci0: Device booted in 12808 usecs
Oct  4 13:58:20 pop-os kernel: [ 9552.688885] Bluetooth: hci0: Found Intel DDC parameters: intel/ibt-19-0-1.ddc
Oct  4 13:58:20 pop-os kernel: [ 9552.703853] Bluetooth: hci0: Applying Intel DDC parameters completed
Oct  4 13:58:20 pop-os kernel: [ 9552.779354] r8169 0000:06:00.1 enp6s0f1: Link is Down
Oct  4 13:58:21 pop-os kernel: [ 9553.564809] wlp0s20f3: authenticate with ac:86:74:bf:2e:30
Oct  4 13:58:21 pop-os kernel: [ 9553.568593] wlp0s20f3: send auth to ac:86:74:bf:2e:30 (try 1/3)
Oct  4 13:58:21 pop-os kernel: [ 9553.579242] iwlwifi 0000:00:14.3: Unhandled alg: 0x707
Oct  4 13:58:21 pop-os kernel: [ 9553.595682] wlp0s20f3: authenticated
Oct  4 13:58:21 pop-os kernel: [ 9553.599545] wlp0s20f3: associate with ac:86:74:bf:2e:30 (try 1/3)
Oct  4 13:58:21 pop-os kernel: [ 9553.601847] wlp0s20f3: RX AssocResp from ac:86:74:bf:2e:30 (capab=0x11 status=0 aid=11)
Oct  4 13:58:21 pop-os kernel: [ 9553.603914] wlp0s20f3: associated
Oct  4 13:58:21 pop-os kernel: [ 9553.609167] IPv6: ADDRCONF(NETDEV_CHANGE): wlp0s20f3: link becomes ready
Oct  4 14:00:54 pop-os kernel: [ 9705.930851] usb 1-4: new full-speed USB device number 5 using xhci_hcd
Oct  4 14:00:54 pop-os kernel: [ 9706.082621] usb 1-4: New USB device found, idVendor=046d, idProduct=c52b, bcdDevice=12.09
Oct  4 14:00:54 pop-os kernel: [ 9706.082629] usb 1-4: New USB device strings: Mfr=1, Product=2, SerialNumber=0
Oct  4 14:00:54 pop-os kernel: [ 9706.082634] usb 1-4: Product: USB Receiver
Oct  4 14:00:54 pop-os kernel: [ 9706.082638] usb 1-4: Manufacturer: Logitech
Oct  4 14:00:54 pop-os kernel: [ 9706.092242] logitech-djreceiver 0003:046D:C52B.0007: hiddev0,hidraw0: USB HID v1.11 Device [Logitech USB Receiver] on usb-0000:00:14.0-4/input2
Oct  4 14:00:54 pop-os kernel: [ 9706.224713] input: Logitech MX Ergo as /devices/pci0000:00/0000:00:14.0/usb1/1-4/1-4:1.2/0003:046D:C52B.0007/0003:046D:406F.0008/input/input47
Oct  4 14:00:54 pop-os kernel: [ 9706.226060] logitech-hidpp-device 0003:046D:406F.0008: input,hidraw1: USB HID v1.11 Keyboard [Logitech MX Ergo] on usb-0000:00:14.0-4/input2:1
Oct  4 14:00:56 pop-os kernel: [ 9708.177867] logitech-hidpp-device 0003:046D:406F.0008: HID++ 4.5 device connected.

**Comment by leviport** [comment]
This appears to have been resolved, but we can reopen if we see it happening again.
