### ISSUE TITLE
gaze17, oryp9: Power button LED stays on during suspend

### ISSUE THREAD

**Issue by linuxgnuru** [system76/firmware-open#323]
### Expected behavior

When the laptop suspends the power button LED either blinks or turns off

### Actual behavior

Power button LED remains on when laptop suspends

**Comment by crawfxrd** [comment]
The power button behavior is the same on proprietary firmware when using s2idle.

**Comment by crawfxrd** [comment]
Fixed by switching from S0ix to S3.

oryp9/oryp10 released, gaze17 pending.
