### ISSUE TITLE
New releases for all models

### ISSUE THREAD

**Issue by crawfxrd** [system76/firmware-open#340]
This is a tracking issue for making a new release for all supported boards. Open new issues for problems found.

- addw2
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/474)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/560)
- bonw14
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/482)
- darp5 (new)
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/479)
- darp6
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/478)
- darp7
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/447)
  - [x] [2023-10-13_5d997d1](https://github.com/system76/firmware/pull/539)
- darp8
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/454)
  - [x] ~[2023-08-18_a8dd6c2](https://github.com/system76/firmware/pull/523)~ yanked due to #469
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/564)
- galp3-c (new)
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/481)
- galp4 (with open EC)
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/480)
- galp5
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/448)
  - [x] [2023-12-12_6f1e653](https://github.com/system76/firmware/pull/538)
- galp6
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/455)
  - [x] [2023-07-19_05cfb1a](https://github.com/system76/firmware/pull/524)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/544)
- gaze15
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/423)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/554)
- gaze16-3050
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/422)
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/541)
- gaze16-3060
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/421)
- gaze16-3060-b
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/420)
- gaze17-3050
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/424)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/518)
- gaze17-3060-b
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/425)
- lemp9
  - [x] [2023-08-18_a8dd6c2](https://github.com/system76/firmware/pull/477)
- lemp10
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/446)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/522)
  - [x] [2023-10-13_5d997d1](https://github.com/system76/firmware/pull/597)
- lemp11
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/443)
  - [x] [2023-07-19_05cfb1a](https://github.com/system76/firmware/pull/521)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/546)
- oryp5 (new)
  - [ ] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/419)
- oryp6
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/418)
- oryp7
  - [x] [2022-11-21_b337ac6](https://github.com/system76/firmware/pull/417)
  - [x] [2023-07-19_05cfb1a](https://github.com/system76/firmware/pull/519)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/555)
- oryp8
  - [x] [2022-10-14_4136ef8](https://github.com/system76/firmware/pull/441)
  - [x] [2023-07-19_05cfb1a](https://github.com/system76/firmware/pull/520)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/556)
- oryp9
  - [x] [2023-06-08_36c78ea](https://github.com/system76/firmware/pull/412)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/557)
- oryp10
  - [x] [2023-06-08_36c78ea](https://github.com/system76/firmware/pull/442)
  - [x] [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/558)

## Resolves

- #160
- #199
- #210
- #218
- #233
- #246
- #266
- #278
- #279
- #282
- #284
- #309
- #342
- #349
- #354
- system76/ec#138
- system76/ec#174

And probably others. It's been a while.

**Comment by curiousercreative** [comment]
@crawfxrd perhaps relevant here, I just built and flashed the latest on my galp5 (for [developing this](https://github.com/pop-os/system76-acpi-dkms/pull/18)) and now I have a new issue that I suspect is a firmware regression. galp5 will suspend normally (blinking green LED but after about four minutes, the green LED goes solid and remains so.

**Comment by curiousercreative** [comment]
@crawfxrd I apologize, I meant to return here and delete my comment as I commented [here](https://github.com/system76/firmware-open/issues/342#issuecomment-1282656131) on an existing issue.

**Comment by larsblumberg** [comment]
Sorry if I hijack this issue. I was wondering if lemp10 receives any firmware update beyond the last official release `2021-07-20_93c2809`?

If not, is there any value for lemp10 owners if they flash the most recent official firmware release, i.e. `2022-11-21`?

**Comment by leviport** [comment]
2021-07-20_93c2809 is the most current for lemp10 at the moment. Since it is shown in the checklist in this issue, an update is planned. Once it passes testing, it will be released.

**Comment by larsblumberg** [comment]
I appreciate you taking the time to respond. And clarifying that the model being listed means it gets an updated. Thank you for our continued support. You are doing an amazing job at System76.

**Comment by crawfxrd** [comment]
ADL boards will need to be updated to coreboot 4.19.

**Comment by crawfxrd** [comment]
Most boards have updates to 2023-05-25_5608a8d staged.

**Comment by x0wllaar** [comment]
Is there any timeframe for general availability of 2023-05-25_5608a8d for lemp11? I'm not getting it in the Firmware Manager GUI :(

**Comment by jacobgkau** [comment]
> Is there any timeframe for general availability of 2023-05-25_5608a8d for lemp11? I'm not getting it in the Firmware Manager GUI :(

2023-07-19_05cfb1a for lemp11 was released today.

**Comment by rvolosatovs** [comment]
Is there any (approximate) timeline for when galp5 could be updated? Interested in secure boot support specifically

**Comment by marcin-rzeznicki** [comment]
#437 was opened by me on the July 11. It took you 2 months to pick it up. Allegedly, it was fixed on the 5th of September, so 4 months have already passed and counting, or 6th months if you count from the time the bug was reported. I will ask again for the nth time. **When are you finally going to release the update** that fixes this $%@#$@, namely [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/557)

**Comment by curiousercreative** [comment]
Understandably you're frustrated with how long firmware bugs take to be looked at, fixed, and eventually released. My galp5 has at least one firmware bug that must be as old as the model itself, I get it. It may already be painfully obvious, but there is far more firmware development, maintenance, and QA demand than supply and, from what I can tell, a lot regressions come from upstream. I'll bet the bugfix you want released was a regression as a result of upstream changes. In my experience, the best way to expedite the release of a fix is to assist with QA. If you're so confident this is resolved, flash your firmware and report back. Many firmware release candidates have more regressions identified and you can help identify those protectively. If you're adventurous enough to flash your firmware, I and others can point you in the right direction.

**Comment by cassanof** [comment]
> #437 was opened by me on the July 11. It took you 2 months to pick it up. Allegedly, it was fixed on the 5th of September, so 4 months have already passed and counting, or 6th months if you count from the time the bug was reported. I will ask again for the nth time. **When are you finally going to release the update** that fixes this @, namely [2023-09-08_42bf7a6](https://github.com/system76/firmware/pull/557)

RELAX, man it's not that hard... i had the issue too and i just looked at the source code of the firmware. you just need to place whatever boot loader you have. see: https://github.com/system76/firmware-open/issues/153

**Comment by cassanof** [comment]
look, took me 3 minutes to find it: https://github.com/system76/firmware-open/blob/master/docs/uefi.md

**Comment by aservedio** [comment]
Personally I share the frustration. The system76 laptop i bought was the most amount of money I ever put in a laptop.

This issue, the fixes those firmware updates contains and its delays into getting it done, is always painful reminder of my mistake with that purchase.

Here's a laptop, thank you for your money, and make sure to not keep it too long coz we won't care about it way faster then its life expectency.

**Comment by cassanof** [comment]
> Personally I share the frustration. The system76 laptop i bought was the most amount of money I ever put in a laptop.
> 
> This issue, the fixes those firmware updates contains and its delays into getting it done, is always painful reminder of my mistake with that purchase.
> 
> Here's a laptop, thank you for your money, and make sure to not keep it too long coz we won't care about it way faster then its life expectency.

I can't disagree more. I've been a customer for almost 4 years. This is a tinkerer's laptop, if you have issues, you can fix them yourself; if you don't like to hack around, then sure, i can see how this may be frustrating. Every part inside your laptop can be replaced if it's faulty, and system76 provides clear instructions on how to. Every single component in your laptop is customizable from a software and hardware point of view.

**Comment by aservedio** [comment]
I don't know how to fully add secureboot/tpm to corebooy bios to install windows 11.

Over a few thinkering sessions I learned how to do it with regedit but then guess what happens if I try to sell the laptop and start explaining that.

I like thinkering, but I would assume at that price tag you'd be able to install windows 11 by now without regedit

**Comment by devoidfury** [comment]
I have an oryp6 that used to be my daily driver. It has problems switching between different graphics modes, compute mode doesn't work at all, and no matter which mode I put it the nvidia drivers never seemed to fully work quite and never got it to work with ML tooling. And really using the card at all makes the machine very loud, the loudest computer I've ever used. After a few years of waiting for firmware updates to try and resolve graphics bugs, switching different distros and kernels, flashing it again, trying different driver versions, looking for workarounds... I went and got a replacement from a different vendor.

I'd be happy to pull it off the shelf and flash firmware on it to help with testing and moving this along if it helps these things work better; I like what you're doing with linux and really want to like system76, but honestly the experience with that laptop put me off it for now. I can't be the only one, maybe if you asked for help with QA in the blog or a newsletter you'd find some more volunteers.

**Comment by curiousercreative** [comment]
@devoidfury can't speak for S76, but I'm sure an oryp6 has had the firmware flashed and appears to be working fine. It's harder to gain confidence that everything under the sun still functions as expected (suspend/resume, Thunderbolt, CPU and GPU PM, etc, etc). All to say, it's most helpful if many adventurous users are daily driving it across some variety of use cases.

**Comment by marcin-rzeznicki** [comment]
> If you're adventurous enough to flash your firmware, I and others can point you in the right direction.

Thanks for the offer, that's very kind of you, but I have already done it - I think I can find my way around. I understand regressions, but even if there are unforeseen problems/bugs, I'd love to have a clear communication e.g. a GH issue or anything that people can track. Everything is better than an unticked checkbox lying dormant for months

**Comment by marcin-rzeznicki** [comment]
> 
> RELAX, man it's not that hard... i had the issue too and i just looked at the source code of the firmware. you just need to place whatever boot loader you have into a specific path, i forget which one. see: #153

The bug is that NVRAM variables are reset randomly - this means that the boot loader path, boot order, timeout and other items are gone and you are booting from something random e.g. from an USB stick you happen to have inserted, or PopOS recovery partition. But usually not from what you want to boot

**Comment by cassanof** [comment]
> > RELAX, man it's not that hard... i had the issue too and i just looked at the source code of the firmware. you just need to place whatever boot loader you have into a specific path, i forget which one. see: #153
> 
> The bug is that NVRAM variables are reset randomly - this means that the boot loader path, boot order, timeout and other items are gone and you are booting from something random e.g. from an USB stick you happen to have inserted, or PopOS recovery partition. But usually not from what you want to boot

Yes, I know. You don't *need* NVRAM variables; there is a hardcoded efi path you can use (`\EFI\BOOT\BOOTX64.EFI`)

**Comment by jackpot51** [comment]
We'll look into the remaining updates not yet released. Most of our products have up to date firmware, a few updates were held due to regressions. Please try to keep discussion on topic, new issues can be created for unrelated items or discussion about old issues can take place om those issues themselves, even if they are already closed.

**Comment by crawfxrd** [comment]
TODO:

- bonw14
- darp6
- gaze16-3050
- gaze16-3060
- gaze16-3060-b

**Comment by yochananmarqos** [comment]
@crawfxrd Adding a TODO then closing the issue is a little confusing...
