### ISSUE TITLE
oryp8: Windows 10 Screen Brightness Controls don't work

### ISSUE THREAD

**Issue by sleepytofu** [system76/firmware-open#355]
- Model: oryp8
- BIOS version: 2022-09-07_74e75ff
- EC version:2022-09-07_74e75ff
- OS: Windows 10

After updating the firmware version 2022-09-07_74e75ff, when booting into Windows 10, the screen is set to a low brightness, and screen brightness controls no longer work.

### Steps to reproduce

1. On Win10 Pro 21H2 (10.0.19044), install Intel UHD graphics driver version 31.0.101.3413, Nvidia Geforce RTX 3080 Laptop, driver version 31.0.15.1694.
2. Bring up the Action Center as shown at https://www.freecodecamp.org/news/how-to-change-screen-brightness-on-windows-10/. Observe the lack of brightness controls.

### Expected behavior

There should be brightness controls, as there were on the previous firmware (2021-09-23_b9b0e89).

### Actual behavior

There are no brightness controls

### Additional info

The brightness controls work on Pop_OS but not Windows 10 on firmware 2022-09-07_74e75ff, and worked in both Pop_OS and Windows on the previous firmware 2021-09-23_b9b0e89

**Comment by crawfxrd** [comment]
Will be fixed with https://github.com/system76/coreboot/pull/137.
