### ISSUE TITLE
oryp8: Not charging while powered on

### ISSUE THREAD

**Issue by crawfxrd** [system76/firmware-open#356]
- Model: oryp8
- BIOS version: 2022-09-07_74e75ff
- EC version: 2022-09-07_74e75ff
- OS: any

The system is not charging on the new release.

### Steps to reproduce

1. Discharge battery to <90%
2. Plug in battery to charge

### Expected behavior

The system immediately starts charging the battery.

### Actual behavior

The system reports "Not Charging" for ~10 seconds, then charges at a very slow rate.

### Additional info

I reverted the EC firmware to the previous release and it still has the problem.

~Kill-A-Watt reports 0.1A and 8W while the system is off.~ I reflashed and it shows the expected values now.

Previous firmware: [oryp8-2021-09-23_b9b0e89.zip](https://github.com/system76/firmware-open/files/9568898/oryp8-2021-09-23_b9b0e89.zip)

**Comment by crawfxrd** [comment]
Kill-A-Watt is reporting 0.24A / 25W will in S3 or S5, which are the expected values.

**Comment by crawfxrd** [comment]
On 2021-09-23_b9b0e89:

```
[oryp8 ~]$ cat /sys/class/power_supply/BAT0/status 
Charging
[oryp8 ~]$ cat /sys/class/power_supply/BAT0/current_now 
1490000
```

`upower -d` reports `pending-charge` and GNOME GUI shows "Not Charging" for a while, but eventually updates.

**Comment by crawfxrd** [comment]
On 2022-09-07_74e75ff:

- `status` changing between "Not Charging" and "Charging several times
- `current_now` swings between 97000 and 625000 (so, not even 1A)

**Comment by crawfxrd** [comment]
I flashed back to 2021-09-23_b9b0e89 and it still has the bad behavior.

**Comment by crawfxrd** [comment]
Works: system76/ec@20d40f347741
Doesn't work: system76/ec@b78631e31606

So caused by: system76/ec#288

**Comment by ahoneybun** [comment]
These are from a customer:

Steps Taken:

1.) upower -d says charge is at 16%.
2.) powered down
3.) unplugged power plug and plugged it back in
4.) left for 5 minutes
5.) powered back on
6.) upower -d says power is at 20%

**Comment by coyotte508** [comment]
Is there an ETA for the firmware upgrade to be available to the public? I don't want to manually mess with the firmware to downgrade it or upgrade it.

**Comment by leviport** [comment]
Probably next week

**Comment by JordanCClark** [comment]
Bumping for an ETA, as I don't know if it got past QC. ;)

**Comment by JordanCClark** [comment]
Came through this evening, Thanks, eveyone!
