### ISSUE TITLE
USB devices should not have generic names

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#36]
On the current firmware, bootable usb devices are listed as `EFI USB Device`, `EFI USB Device 2`, etc. 

On INSYDE firmware, the drives are listed with unique names/descriptions (eg. SanDisk Cruzer). It is much easier to identify a device this way.

**Comment by brs17** [comment]
Should make https://github.com/system76/firmware-open/issues/30 irrelevant.

**Comment by jackpot51** [comment]
Probably fixed by https://github.com/system76/edk2/commit/a45f569149ad88145bb49106e8dafd068e7db3a0

**Comment by brs17** [comment]
@jackpot51 so now I see full drive names in the one time boot menu. I notice that on proprietary firmware it also provides context such as `Linux Boot Manager` and `EFI Hard Drive` (eg. `Linux Boot Manager (Samsung SSD 960 EVO 250GB)`, `EFI Hard Drive (Samsung SSD 960 EVO 250GB)`). 

Would we want to add more information? I would imagine it would make recognizing devices a bit easier/human friendly. Maybe there's an even better way?

**Comment by brs17** [comment]
For whatever reason fix for this seems to have regressed as both Pop!_OS branded generic flash drive and the m.2 enclosure are recognized as `EFI USB Device`

**Comment by jackpot51** [comment]
USB devices have never been named, only directly connected NVMe and SATA devices

**Comment by crawfxrd** [comment]
I found a commit from @MrChromebox's fork which should resolve this, replacing our `HackDevName()` with `BmBootDescription()` from `UefiBootManagerLib`.

![Screenshot from 2020-01-24 13-43-09](https://user-images.githubusercontent.com/5222085/73102690-a2d09900-3eaf-11ea-85f2-5ef6ae552445.png)

**Comment by jackpot51** [comment]
Woot
