### ISSUE TITLE
strange 8-second-long wait for NVS memory upon resume, since firmware upgrade

### ISSUE THREAD

**Issue by ahbarnett** [system76/firmware-open#366]
- Model: pang11
- BIOS version: 1.07.13_S3
- OS: Pop!_OS 22.04

Ever since upgrading firmware from 1.07.08_S3b there has been an additional 8-second delay during resume from sleep (lid open event). Thus I am waiting around 10 seconds for resume, which is annoying and odd. From dmesg I see it is waiting the 8 sec at 
`ACPI: PM: Restoring platform NVS memory`

### Steps to reproduce

open lid when sleeping due to lid-close

### Expected behavior

resume used to take 1 sec or less, as expected.

### Actual behavior

8 sec extra delay doing nothing (blank screen) before resume

### Additional info

Relevant part of system log from dmesg:

```
[1514416.708191] ACPI: PM: Low-level resume complete
[1514416.708218] ACPI: EC: EC started
[1514416.708218] ACPI: PM: Restoring platform NVS memory
[1514424.905096] LVT offset 0 assigned for vector 0x400
[1514424.905736] Enabling non-boot CPUs ...
[1514424.905809] x86: Booting SMP configuration:
```

I attach full dmesg and lspci -v :

[dmesg.out.txt](https://github.com/system76/firmware-open/files/9814013/dmesg.out.txt)
[lspci-v.out.txt](https://github.com/system76/firmware-open/files/9814015/lspci-v.out.txt)

Thanks so much, Alex

**Comment by crawfxrd** [comment]
pang11 is not a firmware-open model. Please open a ticket with support.
