### ISSUE TITLE
System ocassionally hangs at BIOS splash screen

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#38]
Steps to reproduce issue:
1. System is off
2. Plug in external harddrive with firmware written to it.
3. Press <kbd>Esc</kbd> when System76 logo appears.
4. See system sit for quite a while before eventually getting into the BIOS menu.

**Comment by brs17** [comment]
Now this seems to happen most often when the PXEstick is still connected after reboot after using the PXEstick to PXE boot.

**Comment by crawfxrd** [comment]
Most USB issues fixed with newer edk2 releases.
