### ISSUE TITLE
Thunderbolt issues

### ISSUE THREAD

**Issue by jackpot51** [system76/firmware-open#4]
Thunderbolt works better when using this kernel parameter:

```
pci=assign-busses,hpmemsize=1G,hpbussize=8
```

**Comment by jackpot51** [comment]
It is likely the configured BAR sizes are invalid in coreboot

**Comment by jackpot51** [comment]
A 90 second timeout occurs during resume sometimes:

```
[  351.674241] thunderbolt 0000:03:00.0: failed to send driver ready to ICM
```

**Comment by brs17** [comment]
Going to close this issue as the 90 second timeout seems to have been resolved. Other Thunderbolt related issues should be created as their own issue.
