### ISSUE TITLE
"Enter" key is required multiple times to update firmware

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#40]
When booting into the firmware updater to update firmware, the user is prompted twice to press <kbd>Enter</kbd>.

There should only be one prompt for an <kbd>Enter</kbd>

**Comment by jackpot51** [comment]
This was solved in https://github.com/system76/firmware-update/commit/7d211482786bf8d099d6891c3c9eb29b3fa39f4d

**Comment by brs17** [comment]
You right.
