### ISSUE TITLE
Keyboard input sometimes doesn't work at boot

### ISSUE THREAD

**Issue by JordanBoulan** [system76/firmware-open#406]
Basically, just the title.

Issue 1: I've noticed that sometimes hitting ESC just simply does nothing, even when mashing. This issue often seems to appear right before issue 2. Or in other words issue two seems to immediately follow issue 1 after rebooting 2-3 times to get issue 1 fixed.

Issue 2: There is also this bug where it goes into the settings but then the keyboard and arrow keys don't work and you can't do anything and are forced to reboot. This no input working in UEFI seems to persist across multiple reboots and I find myself having to reboot the laptop 5+ times just to get into UEFI with input actually working so I am able to select a boot option.

Anyone else have this issue?

**Comment by leviport** [comment]
When this happens, does a USB keyboard work normally? This would help determine whether it's just a problem with the built-in keyboard, which could be an EC thing, or something else entirely.

**Comment by dni** [comment]
seeing the same issue the first time after updating firmware on pang12, very frustrating, for me i yet wasnt able to get into bios

**Comment by dni** [comment]
not sure what happened, but turning off and on the ps2 support inside BIOS fixed this issue for me. Also the issue i had why i updated firmware in the first place, was because the touchpad suddenly stopped working, which also gone away.

**Comment by leviport** [comment]
@dni the pang12 does not have open firmware, so this issue is unrelated to any of that.

**Comment by crawfxrd** [comment]
May be solved by https://github.com/system76/ec/pull/377.

**Comment by dni** [comment]
i found my issue is probably hardware related one. everytime it happens i apply some pressure on the top right corner of the touchpad and it starts to work again for some time. pretty annoying, but it works.

**Comment by leviport** [comment]
Sounds like re-seating the FFC connections to the touchpad might help. Fonzi-style workarounds tend to stop working after a while.
