### ISSUE TITLE
After declining firmware update in firmware updater, rebooting takes over 70 seconds

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#41]
~With a USB device plugged in (usb 2 or 3.*), a reboot of the system takes over 70 seconds to get back to the System76 BIOS splash screen. This reboot can happen from either the BIOS menu or the operating system itself.~

EDIT:

After further investigation, I found that if I decline to do a firmware update while in the firmware updater (by pressing <kbd>Space</kbd>), then every subsequent reboot takes over 70 seconds (to get to the System76 BIOS splash screen). Once the system is completely powered off, the issue will no longer persist.

**Comment by crawfxrd** [comment]
Stale, can't reproduce.
