### ISSUE TITLE
Fix or remove MinPlatform support

### ISSUE THREAD

**Issue by crawfxrd** [system76/firmware-open#449]
[MinPlatform](https://github.com/tianocore/edk2-platforms/blob/4507df44c5282b23a8a6ab5dfa5b6565b122139e/Platform/Intel/Readme.md) only worked with the KBL-U boards. I suppose it built at one point? I can't get it to build currently.

Is it worth getting this working again? Do we care to ever have edk2-specific PEI firmware?

---

If removed, we'd be able to remove the following submodules:

- edk2-non-osi
- edk2-platforms
- FSP

And the following scripts:

- `udk.sh`
- `udk-debug.gdb`
- `udk-output.sh`
- `udk-server.sh`
- `minplatform.sh`

**Comment by jackpot51** [comment]
I recommend to remove it.
