### ISSUE TITLE
Does not compile for galp3

### ISSUE THREAD

**Issue by as4000** [system76/firmware-open#45]
Error:

src/cpu/x86/Makefile.inc:21: *** Halting the build due to unknown TARGET_STAGE select.  Stop.

**Comment by jackpot51** [comment]
I updated the configs for older models so galp3 will compile now.

Please note that only the darp6 and galp4 are officially supported - if you brick your device it will be up to you to restore the current firmware using an external programmer.

**Comment by as4000** [comment]
Are you saying that it just doesn't work for galp3 ?

Are you going to support older models at all ?

**Comment by jackpot51** [comment]
We expect to develop official open firmware for older models after the newest models are shipping.
