### ISSUE TITLE
Error installing dependencies to build the firmware (downloading acpica-unix2-20220331.tar.gz fails for unknown reasons)

### ISSUE THREAD

**Issue by k4l1mi5t** [system76/firmware-open#453]
- Model: lemp10
- BIOS version: 2022-11-21_b337ac6
- EC version: 2022-11-21_b337ac6
- OS: Pop!_OS 22.04 LTS
- Kernel: 6.4.6-76060406-generic

I'm trying to adjust the fancurve on my lemur as it's a bit to agressive for my taste, spinning up for a couple of seconds and stopping again, over and over. 

I run into an error installing the dependencies to build the firmware.

### Steps to reproduce

```
git clone https://github.com/system76/firmware-open.git
cd firmware-open
git checkout b337ac6
git submodule init
git submodule update
sudo ./scripts/deps.sh
```

### Expected behavior

Running the deps.sh script will successfully install needed dependencies to build the firmware.

### Actual behavior

Script errors out trying to download acpica-unix2-20220331.tar.gz

### Additional info

```
Downloading and verifying tarballs ...
 * acpica-unix2-20220331.tar.gz (downloading from https://acpica.org/sites/acpica/files/acpica-unix2-20220331.tar.gz)...   0%... Failed to download acpica-unix2-20220331.tar.gz.
make[1]: *** [Makefile:23: build_iasl] Error 1
make: *** [util/crossgcc/Makefile.inc:30: crossgcc-i386] Error 2
Failed to install dependencies!
```

**Comment by crawfxrd** [comment]
Intel has removed the acpica.org site. It now just redirects to ACPICA page intel.com. You need to use a newer version of coreboot, or download the archive from somewhere else (archive.org, GitHub).

**Comment by k4l1mi5t** [comment]
Thank you, that worked out. Only thing is if I don't run the script as root, it's not able to lock the directory /var/lib/apt/lists/. See the following error:

Installing EC dependencies
~/gits/firmware-open/ec ~/gits/firmware-open
Installing system build dependencies
Reading package lists... Done
E: Could not get lock /var/lib/apt/lists/lock. It is held by process 1589 (packagekitd)
N: Be aware that removing the lock file is not a solution and may break your system.
E: Unable to lock directory /var/lib/apt/lists/
Failed to install dependencies!
Failed to install dependencies!

You can leave it as closed as my issue is resolved.
