### ISSUE TITLE
Dual booting and systemd-boot menu

### ISSUE THREAD

**Issue by leviport** [system76/firmware-open#47]
When a dual boot is set up with two separate EFI partitions, Pop must be the default boot option in order to access the systemd-boot menu. Holding spacebar after selecting the Pop entry does nothing and the machine boots straight into Pop.

**Comment by brs17** [comment]
Appears to be resolved with : https://github.com/system76/edk2/commit/b6d3cf4d883a9d2fd35395af5469d8adf1c002ea
