### ISSUE TITLE
Should later firmware version than that provided upstream result in notification?

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#49]
There was discussion when seeing fwupd devices that had a newer version of firmware than was on fw-upd, that the user should not be notified of this "newer" firmware as it probably is not newer -firmware but just a lack updating fwupd.

I am wondering if we want to do the same thing with this firmware as the version includes the date. Potentially a version with a newer date should not notify that a firmware of an earlier date is a newer version.

Example:

Have 
2019-10-23... installed and firmware-manager notifies that 2019-10-08... is the latest version.

**Comment by crawfxrd** [comment]
Any unreleased or custom firmware should prompt to update to the latest System76 release.

Disabling those notifications would be a separate issue for firmware-manager.
