### ISSUE TITLE
`bonw15` speakers are cutting in and out

### ISSUE THREAD

**Issue by ahoneybun** [system76/firmware-open#495]
- Model: bonw15
- BIOS version: 2023-07-10_0e4a64a
- EC version: 2023-07-10_0e4a64a
- OS: Ubuntu 22.04 and Pop!_OS
- Kernel: 6.5.4-76060504-generic

Playing certain audio files seems to cause a pause in the audio (the file keeps playing).

### Steps to reproduce

Play the file with either Totem or VLC (snap or deb).

### Expected behavior

Audio keeps playing without issue

### Actual behavior

The audio is cutting in and out but the content is still playing.

### Additional info

Happens in different users and in a live disk, seems to play fine with headphones.

**Comment by fleaplus** [comment]
Applying a similar fix as this from the serw13 helped my bonw15 with the same issue:

https://github.com/system76/coreboot/commit/e6f70bdcb5ad03f8a2e4b14e09a5da1d174a9a73
