### ISSUE TITLE
Issues with multiple OS installs from USB

### ISSUE THREAD

**Issue by leviport** [system76/firmware-open#50]
I was testing dual boot on a Galago. I first started by flashing the latest firmware (as of October 22nd) then flashing Pop 19.10. I then installed Ubuntu 18.04 on the second drive in the machine, then clean installed Pop 19.10 back over the same drive it was initially imaged onto. After this, I tried reinstalling Ubuntu 18.04, but the installer kept failing on both drives. I then reinstalled the same firmware version and tried Pop 19.10 and 18.04 several times each, from different USB drives, installing to both internal drives, and the installer would fail every time. 

At one point, I was trying to boot to one of our M.2 enclosures with 19.10 on it, and the BIOS menu broke completely, and it is stuck in that state. The machine now boots directly into BIOS without showing the splash screen. Selecting "Boot Default" does nothing, and no boot options are shown in "One Time Boot" or "Change Boot Order". I will leave the machine as-is for further investigation.

![IMG_20191023_172204](https://user-images.githubusercontent.com/13512097/67441575-9e4bca00-f5ba-11e9-8e28-cc621d9724fe.jpg)

**Comment by brs17** [comment]
An attempt needs to be made to recreate this issue as it is not usually seen in normal use.
