### ISSUE TITLE
lemp10 not waking up from standby with latest firmware 2023-09-08_42bf7a6

### ISSUE THREAD

**Issue by larsblumberg** [system76/firmware-open#500]
- Model: `lemp10`
- BIOS version: `2023-09-08_42bf7a6`
- EC version: same version
- Kernel: `6.5.4-76060504-generic`

### Steps to reproduce

1. Wait for lemp10 to go to standby by not touching it
2. lemp10 goes to standby
3. Press any key or touch pad to wake up: nothing happens
4. Notice that power LED is permanently on
5. Holding power button pressed ~15-20 seconds turns lemp10 and allows for rebooting

### Expected behavior

lemp10 should wake up on key pressed when in standby

### Actual behavior

lemp10's screen stays black

### Additional info

Proof of current firmware:

![image](https://github.com/system76/firmware-open/assets/5980316/1e89c190-63af-4279-af28-c99b72fbc57e)

Problem did not show prior to this latest firmware update. Wake up from standby did work reliably.

**Comment by crawfxrd** [comment]
Latest firmware is 2023-10-13_5d997d1, which fixes this issue.
