### ISSUE TITLE
scripts/install-deps.sh fails due to undeclared TARGET

### ISSUE THREAD

**Issue by liam-clink** [system76/firmware-open#512]
- Model:  serw13
- BIOS version:  2023-09-19_16ef69c
- EC version:  2023-09-19_16ef69c
- OS:  Pop!_OS 22.04 LTS x86_64
- Kernel:  6.6.10-76060610-generic

When running scripts/install-deps.sh I get this error when binutils 2.37 is being built:

```
../../binutils-2.37/binutils/bucomm.c:154:24: error: 'TARGET' undeclared (first use in this function)
  154 |   const char *target = TARGET;
      |                        ^~~~~~
```

### Steps to reproduce

`./scripts/install-deps.sh`

### Expected behavior

Successful installation of dependencies

### Actual behavior

Failure of building binutils cuts the installation short

### Additional info

Using current master commit [3e19b73](https://github.com/system76/firmware-open/commit/3e19b73397c27cf88b048902a3f080f584d0f851)

**Comment by crawfxrd** [comment]
I can't reproduce this. I'm not even sure how you would make it happen.
