### ISSUE TITLE
Error when running build.sh script

### ISSUE THREAD

**Issue by YerimB** [system76/firmware-open#520]
- Model: addw3
- BIOS version: 2023-08-23_8173119
- EC version: Never flashed
- OS: Manjaro KDE
- Kernel: 6.6.16-2-MANJARO

I'm getting an `make` error after some time when running `./scripts/build.sh addw3`.

### Steps to reproduce

I am on the branch `master` and followed the `README.md` instructions by running the following commands successively:

```sh
./scripts/install-deps.sh
source ~/.cargo/env
./scripts/build.sh addw3 # Error occurs here
```

### Actual behavior

After some time of the command running I'm getting the following output:

```
'build/coreboot.rom' -> '/home/yem/Softwares/firmware-open/build/addw3/firmware.rom'
  CC        scratch/board/system76/common/scratch/../smfi.rel
  CC        scratch/board/system76/common/scratch/main.rel
  CC        scratch/board/system76/common/scratch/stdio.rel
  LINK      scratch/scratch.ihx
  OBJCOPY   scratch/scratch.rom
  XXD       include/scratch.h
  CC        flash/board/system76/common/flash/main.rel
  LINK      flash/flash.ihx
  OBJCOPY   flash/flash.rom
  XXD       include/flash.h
  CC        board/system76/common/main.rel
  CC        arch/8051/arch.rel
  ...
  CC        board/system76/common/pnp.rel
src/board/system76/addw3/gpio.c:37: error 283: function declarator with no prototype
  CC        board/system76/common/power.rel
  CC        board/system76/common/ps2.rel
  CC        board/system76/common/pwm.rel
  CC        board/system76/common/scratch.rel
  CC        board/system76/common/security.rel
make: *** [src/arch/8051/toolchain.mk:52: build/board/system76/addw3/gpio.rel] Error 1
make: *** Waiting for unfinished jobs....
  CC        board/system76/common/smbus.rel
```

### Additional info

The only changes I made are in the submodule `ec`:

Modified `ec/src/board/system76/addw3/board.mk`: Updated the fan points (Double checked it).  
Created `ec/config.mk` to try running `make` directly in `ec/`:
```mk
# cat ec/config.mk
BOARD?=system76/addw3
```

**Comment by crawfxrd** [comment]
Already fixed in https://github.com/system76/ec/pull/417.

You either need to use a newer EC commit or downgrade SDCC.
