### ISSUE TITLE
With no boot options available, provide message about missing boot device

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#53]
Currently if there are no boot options available and the boot entries are properly removed, the `Boot Default` option does nothing and the `One Time Boot` menu is blank. This is completely as expected.

I wonder if a message should be shown to notify that there are no detected boot devices. As one may think selecting `Boot Default` and not getting a response is a broken state.

**Comment by crawfxrd** [comment]
Duplicate of #6?

**Comment by brs17** [comment]
Looks like I had different experiences on the `One Time Boot` menu in each of these issues (you may want to look and see what the current behavior is), but yes I think it is a duplicate.
