### ISSUE TITLE
rust nightly required?

### ISSUE THREAD

**Issue by randomuygvruyv65423654** [system76/firmware-open#533]
I get errors when I try to build firmware.
error[E0554]: `#![feature]` may not be used on the stable release channel
The components which have redox uefi as a dependency are the ones with this issue. I'm using the version of rust which comes packaged with Debian 12 which is rustc 1.63.0 presumably stable build. The error seems to indicate that the nightly build is required. For reasons I don't want to get into I'd rather not use the nightly build. Is it possible to build the firmware with rust stable?

**Comment by crawfxrd** [comment]
If you're not using the version of the toolchain specified by the toolchain file then you're environment is not set up correctly.

It is not possible to build with a stable toolchain.
