### ISSUE TITLE
Intel Meteor Lake does not show NPU support

### ISSUE THREAD

**Issue by ahoneybun** [system76/firmware-open#580]
- Model: darp10-b
- BIOS version: 2024-09-11_351d80d
- EC version: 2024-09-11_351d80d
- OS: Pop!_OS 22.04
- Kernel: 6.9.3

https://community.intel.com/t5/Wireless/Meteor-Lake-PCH-CNVi-Wi-Fi-6E-AX211-not-working-with-Linux/m-p/1627132

From the `lspci` output should show the NPU but on the darp10 (Ultra 5 and 7) do not report this. I suspect that the other 14th Gen Models will also not list this.

### Steps to reproduce

1. Boot Pop!_OS 22.04 (or any other Linux OS)
2. Run `lspci` and note that the NPU is missing:

### Expected behavior

Something like this should appear in that output:

00:0b.0 Processing accelerators: Intel Corporation Meteor Lake NPU (rev 04)

### Actual behavior

The output is missing

**Comment by crawfxrd** [comment]
Device is disabled by default in coreboot. Needs an override to be enabled.

- https://github.com/system76/coreboot/blob/24.08/src/soc/intel/meteorlake/chipset.cb#L70
