### ISSUE TITLE
Documentation for firmware-open does not build.

### ISSUE THREAD

**Issue by allanwmacdonald** [system76/firmware-open#581]
- Model: addw3
- BIOS version: 2024-07-08_926f73d
- EC version: 
- OS: Pop!_OS 22.04 LTS
- Kernel:6.9.3-76060903-generic

mdbook build fails in firmware-open repository

### Steps to reproduce

1. sudo snap install mdbook
2. git clone https://github.com/system76/firmware-open.git
3. cd firmware-open
4. mdbook build --open docs/
 
### Expected behavior
Book is created.

### Actual behavior

Following error message is displayed:

> An error occured:
> Unable to open the configuration file

### Additional info

Just following instructions here:
https://github.com/system76/firmware-open/blob/master/docs/index.md

**Comment by crawfxrd** [comment]
Don't use snap shit.

```
$ mdbook --version
mdbook v0.4.37
$ mdbook build docs
2024-10-14 07:53:13 [INFO] (mdbook::book): Book building has started
2024-10-14 07:53:13 [INFO] (mdbook::book): Running the html backend
```
