### ISSUE TITLE
Handle case of having no bootable disk installed

### ISSUE THREAD

**Issue by brs17** [system76/firmware-open#6]
On a Darter Pro:

After having installed Pop!_OS 19.04 to a NVMe drive, I removed the drive. Upon booting the system, I was taken to an EFI shell that gives the message that there is nothing to mount. Going into the bios, I still see Pop!_OS 19.04, Linux Boot Manager, and an EFI shell as bootable options.

On proprietary firmware provided by upstream, in a similar situation, the system shows a message: `Default Boot Device Missing or Boot Failed. Insert Recovery Media and Hit any key Then Select 'Boot Manager' to choose a new Boot Device or to Boot Recovery Media`. In the bios menu there are no selectable options from which to boot.

I think it is important in this situation to make it clear to the user that there is no bootable media immediately available.

**Comment by crawfxrd** [comment]
Current behavior is that of #53: empty list for "One Boot Time" and "Change Boot Order", "Boot Default" reloads the front page (so no user visible behavior).

With system76/edk2#7, a warning will be printed if no devices are found:

![Screenshot from 2020-01-29 07-58-43](https://user-images.githubusercontent.com/5222085/73367934-6e712a00-426d-11ea-925b-5f4749e27711.png)

**Comment by crawfxrd** [comment]
Will be resolved with #77.
