### ISSUE TITLE
Change Boot Order is not saving

### ISSUE THREAD

**Issue by ahoneybun** [system76/firmware-open#60]
Hardware:
galp4

WD Green 240GB M.2 SSD
SeaGate FireCuda 2TB 

Firmware:
2019-10-31_cca6ad0

Tried two different orders:
1. Click Change Boot Order
2. Change the drive order with Pg Up/Pg Down
3. Commit Changes and Exit

---

1. Click Change Boot Order
2. Change the drive order with Pg Up/Pg Down
3. Hit F10 to save
4. Commit Changes and Exit

Ticket for information:
https://system76.com/admin/support/view/41374

**Comment by brs17** [comment]
Turns out this was just user error.
