### ISSUE TITLE
Support for coreboot payloads?

### ISSUE THREAD

**Issue by muevoid** [system76/firmware-open#69]
Hello I am aware that on other laptops that use vanilla coreboot it is possible to use other payloads such as a grub2 payload or seabios. Is this possible with this implementation? If not what is stopping from doing so?

**Comment by igalic** [comment]
i would love to be able to get some insight into the machine, and perhaps disable some features i don't need

**Comment by crawfxrd** [comment]
I don't see why not. Our fork just adds support for System76 mainboard targets (plus carries [35802](https://review.coreboot.org/c/coreboot/+/35802)). It's not something we will do or support, though.

**Comment by crawfxrd** [comment]
Closing this since we won't support other payloads.
