### ISSUE TITLE
question: Why system76 doesn't ship it's computers to Bangladesh?

### ISSUE THREAD

**Issue by mobop** [system76/firmware-open#73]

**Comment by strugee** [comment]
This kind of question is appropriate for sales, not for a bug tracker. https://system76.com/contact

(I am not affiliated with System76.)

**Comment by leviport** [comment]
That's correct, you should reach out to the sales team. I know we try to ship as many places as possible, so I'd imagine it's an import restriction or something like that. Thank you for your interest though!
