### ISSUE TITLE
lemp9 windows support

### ISSUE THREAD

**Issue by thomas-zimmerman** [system76/firmware-open#89]
Customer would like to have the following support while in windows10:

- [x] Brightness display working from function keys

- [ ] Enable/Disable touch pad function key

- [x] Battery charging status change when AC power plugged/unplugged

**Comment by jackpot51** [comment]
I'm not sure how to enable the touchpad function key without writing windows code

**Comment by jackpot51** [comment]
Fixed the other two, and prepared firmware updates

**Comment by ahoneybun** [comment]
Any update on this firmware update now that it was reverted? Are we working on this in a new firmware update?

**Comment by leviport** [comment]
We're still getting to the bottom of it. It's a tricky one.

**Comment by ahoneybun** [comment]
Anything new on this one? Thank you.

**Comment by jackpot51** [comment]
The firmware has been released
