### ISSUE TITLE
Feature Request: Hide Pop Shell Panel Icon

### ISSUE THREAD

**Issue by mannotserious** [system76/firmware-open#92]
I use and love the tiling function of the Pop Shell. However, I don't want to see the icon in the panel. The option to hide it whilst retaining funcionality would be great. As there is a hotkey to toggle window tiling the panel icon is never used.
Great work on 20.04 guys I will continue to donate to you!!

Cheers from New Zealand!

**Comment by WatchMkr** [comment]
We may provide this option once tiling settings are present in system settings. 

Going to close for now. Please put future tiling request in the pop-shell repo. Thanks!

**Comment by PixsaOJ** [comment]
I created [issue](https://github.com/pop-os/shell/issues/1274) on pop-shell repository.
