### ISSUE TITLE
Error during build/x86_64-efi-pe/efi.img.tmp creation (darp6 model)

### ISSUE THREAD

**Issue by ghost** [system76/firmware-open#95]
I got that : 
![Capture d’écran de 2020-06-18 16-52-54](https://user-images.githubusercontent.com/45756534/85036055-2a32e780-b184-11ea-91fb-5ce2bb15d498.png)

mkfs.vfat command is not found. Perhaps sudo is needed ?

**Comment by crawfxrd** [comment]
`dosfstools` needs to be installed. Have you run `scripts/deps.sh`?

**Comment by neox95** [comment]
I have dosfstools installed and I use mkfs.vfat quite often

**Comment by neox95** [comment]
![Capture d’écran de 2020-06-18 17-15-27](https://user-images.githubusercontent.com/45756534/85038842-58fe8d00-b187-11ea-92ef-e15c201e64bb.png)

**Comment by crawfxrd** [comment]
`sudo` is not required since we are writing to a file and not a block device.

This is occurring in `scripts/pxestick.sh`. We don't override `PATH` so be able to find it. Does `which mkfs.vfat` find it?

**Comment by neox95** [comment]
Seems to be a path problem with debian
![Capture d’écran de 2020-06-18 17-29-24](https://user-images.githubusercontent.com/45756534/85040623-4ab17080-b189-11ea-9a8c-46c6daacd79c.png)

**Comment by neox95** [comment]
Note : I've just tried compiling within su and it works without problem

**Comment by crawfxrd** [comment]
This should be sufficient:

```
PATH=$PATH:/usr/sbin ./scripts/build.sh darp6
```

The patched version of parted 3.2 in Debian will produce permission errors trying to read the SMBIOS entry point. These aren't significant (and sent to `/dev/null` in 3.3).
